// Generated from the local legacy router inventory for migration tracking.
// Keep route URLs/names stable until each pending view is migrated and verified.

export type LegacyRouteMigrationStatus = 'pending-view' | 'migrated' | 'removed'

export interface LegacyRouteDescriptor {
  readonly sourceModule: string
  readonly sourceFile: string
  readonly legacyPath: string
  readonly path: string
  readonly name: string
  readonly legacyView: string
  readonly legacyIndex: number
  readonly status: LegacyRouteMigrationStatus
  readonly note?: string
}

export const legacyRouteManifest = [
  {
    sourceModule: "aboutAs",
    sourceFile: "src/router/modules/aboutAs.js",
    legacyPath: "/setting/aboutAs",
    path: "/setting/aboutAs",
    name: "aboutAs",
    legacyView: "@/views/mine/aboutAs.vue",
    legacyIndex: 13,
    status: 'pending-view',
  },
  {
    sourceModule: "addAddress",
    sourceFile: "src/router/modules/addAddress.js",
    legacyPath: "/mine/addAddress",
    path: "/mine/addAddress",
    name: "addAddress",
    legacyView: "@/views/mine/addAddress.vue",
    legacyIndex: 13,
    status: 'pending-view',
  },
  {
    sourceModule: "advertisementPool",
    sourceFile: "src/router/modules/advertisementPool.js",
    legacyPath: "/pool/advertisementPool",
    path: "/pool/advertisementPool",
    name: "advertisementPool",
    legacyView: "@/views/pool/advertisementPool.vue",
    legacyIndex: 15,
    status: 'pending-view',
  },
  {
    sourceModule: "appeal",
    sourceFile: "src/router/modules/appeal.js",
    legacyPath: "/order/appeal",
    path: "/order/appeal",
    name: "appeal",
    legacyView: "@/views/order/appeal.vue",
    legacyIndex: 3,
    status: 'migrated',
  },
  {
    sourceModule: "appealDetail",
    sourceFile: "src/router/modules/appealDetail.js",
    legacyPath: "/order/appealDetail",
    path: "/order/appealDetail",
    name: "appealDetail",
    legacyView: "@/views/order/appealDetail.vue",
    legacyIndex: 13,
    status: 'migrated',
  },
  {
    sourceModule: "appealRecord",
    sourceFile: "src/router/modules/appealRecord.js",
    legacyPath: "/order/appealRecord",
    path: "/order/appealRecord",
    name: "appealRecord",
    legacyView: "@/views/order/appealRecord.vue",
    legacyIndex: 12,
    status: 'migrated',
  },
  {
    sourceModule: "areaNode",
    sourceFile: "src/router/modules/areaNode.js",
    legacyPath: "/node/areaNode",
    path: "/node/areaNode",
    name: "areaNode",
    legacyView: "@/views/node/areaNode.vue",
    legacyIndex: 15,
    status: 'pending-view',
  },
  {
    sourceModule: "balanceWallet",
    sourceFile: "src/router/modules/balanceWallet.js",
    legacyPath: "/wallet/balanceWallet",
    path: "/wallet/balanceWallet",
    name: "balanceWallet",
    legacyView: "@/views/wallet/balanceWallet.vue",
    legacyIndex: 15,
    status: 'pending-view',
  },
  {
    sourceModule: "brandSpike",
    sourceFile: "src/router/modules/brandSpike.js",
    legacyPath: "/brandSpike",
    path: "/brandSpike",
    name: "brandSpike",
    legacyView: "@/views/brandSpike/index",
    legacyIndex: 2,
    status: 'migrated',
  },
  {
    sourceModule: "cancelOrder",
    sourceFile: "src/router/modules/cancelOrder.js",
    legacyPath: "/order/cancelOrder",
    path: "/order/cancelOrder",
    name: "cancelOrder",
    legacyView: "@/views/order/cancelOrder.vue",
    legacyIndex: 11,
    status: 'migrated',
  },
  {
    sourceModule: "chainCatSpike",
    sourceFile: "src/router/modules/chainCatSpike.js",
    legacyPath: "/chainCatSpike",
    path: "/chainCatSpike",
    name: "chainCatSpike",
    legacyView: "@/views/chainCatSpike/index",
    legacyIndex: 2,
    status: 'migrated',
  },
  {
    sourceModule: "changePassword",
    sourceFile: "src/router/modules/changePassword.js",
    legacyPath: "/mine/changePassword",
    path: "/mine/changePassword",
    name: "changePassword",
    legacyView: "@/views/mine/changePassword.vue",
    legacyIndex: 14,
    status: 'pending-view',
  },
  {
    sourceModule: "cityNode",
    sourceFile: "src/router/modules/cityNode.js",
    legacyPath: "/node/cityNode",
    path: "/node/cityNode",
    name: "cityNode",
    legacyView: "@/views/node/cityNode.vue",
    legacyIndex: 15,
    status: 'pending-view',
  },
  {
    sourceModule: "consumerWallet",
    sourceFile: "src/router/modules/consumerWallet.js",
    legacyPath: "/wallet/consumerWallet",
    path: "/wallet/consumerWallet",
    name: "consumerWallet",
    legacyView: "@/views/wallet/consumerWallet.vue",
    legacyIndex: 15,
    status: 'pending-view',
  },
  {
    sourceModule: "consumptionPool",
    sourceFile: "src/router/modules/consumptionPool.js",
    legacyPath: "/pool/consumptionPool",
    path: "/pool/consumptionPool",
    name: "consumptionPool",
    legacyView: "@/views/pool/consumptionPool.vue",
    legacyIndex: 15,
    status: 'pending-view',
  },
  {
    sourceModule: "countryRegion",
    sourceFile: "src/router/modules/countryRegion.js",
    legacyPath: "/mine/countryRegion",
    path: "/mine/countryRegion",
    name: "countryRegion",
    legacyView: "@/views/mine/countryRegion.vue",
    legacyIndex: 15,
    status: 'pending-view',
  },
  {
    sourceModule: "emailRegister",
    sourceFile: "src/router/modules/emailRegister.js",
    legacyPath: "/register/emailRegister",
    path: "/register/emailRegister",
    name: "emailRegister",
    legacyView: "@/views/register/emailRegister",
    legacyIndex: 2,
    status: 'migrated',
  },
  {
    sourceModule: "emailRegisterTwo",
    sourceFile: "src/router/modules/emailRegisterTwo.js",
    legacyPath: "/register/emailRegisterTwo",
    path: "/register/emailRegisterTwo",
    name: "emailRegisterTwo",
    legacyView: "@/views/register/emailRegisterTwo",
    legacyIndex: 3,
    status: 'migrated',
  },
  {
    sourceModule: "feedback",
    sourceFile: "src/router/modules/feedback.js",
    legacyPath: "/mine/feedback",
    path: "/mine/feedback",
    name: "feedback",
    legacyView: "@/views/mine/feedback.vue",
    legacyIndex: 15,
    status: 'pending-view',
  },
  {
    sourceModule: "forgetPassword",
    sourceFile: "src/router/modules/forgetPassword.js",
    legacyPath: "/mine/forgetPassword",
    path: "/mine/forgetPassword",
    name: "forgetPassword",
    legacyView: "@/views/mine/forgetPassword.vue",
    legacyIndex: 14,
    status: 'migrated',
  },
  {
    sourceModule: "foundGoodGoods",
    sourceFile: "src/router/modules/foundGoodGoods.js",
    legacyPath: "/foundGoodGoods",
    path: "/foundGoodGoods",
    name: "foundGoodGoods",
    legacyView: "@/views/foundGoodGoods/index",
    legacyIndex: 2,
    status: 'migrated',
  },
  {
    sourceModule: "helpCenter",
    sourceFile: "src/router/modules/helpCenter.js",
    legacyPath: "/mine/helpCenter",
    path: "/mine/helpCenter",
    name: "helpCenter",
    legacyView: "@/views/mine/helpCenter.vue",
    legacyIndex: 14,
    status: 'pending-view',
  },
  {
    sourceModule: "industryNode",
    sourceFile: "src/router/modules/industryNode.js",
    legacyPath: "/node/industryNode",
    path: "/node/industryNode",
    name: "industryNode",
    legacyView: "@/views/node/industryNode.vue",
    legacyIndex: 15,
    status: 'pending-view',
  },
  {
    sourceModule: "login",
    sourceFile: "src/router/modules/login.js",
    legacyPath: "/login",
    path: "/login",
    name: "login",
    legacyView: "@/views/login/index",
    legacyIndex: 2,
    status: 'migrated',
  },
  {
    sourceModule: "loveShop",
    sourceFile: "src/router/modules/loveShop.js",
    legacyPath: "/loveShop",
    path: "/loveShop",
    name: "loveShop",
    legacyView: "@/views/loveShop/index",
    legacyIndex: 2,
    status: 'migrated',
  },
  {
    sourceModule: "messageCenter",
    sourceFile: "src/router/modules/messageCenter.js",
    legacyPath: "/mine/messageCenter",
    path: "/mine/messageCenter",
    name: "messageCenter",
    legacyView: "@/views/mine/messageCenter.vue",
    legacyIndex: 14,
    status: 'pending-view',
  },
  {
    sourceModule: "myFocus",
    sourceFile: "src/router/modules/myFocus.js",
    legacyPath: "/myFocus",
    path: "/myFocus",
    name: "myFocus",
    legacyView: "@/views/myFocus/index",
    legacyIndex: 2,
    status: 'pending-view',
  },
  {
    sourceModule: "myWallet",
    sourceFile: "src/router/modules/myWallet.js",
    legacyPath: "/wallet/myWallet",
    path: "/wallet/myWallet",
    name: "myWallet",
    legacyView: "@/views/wallet/myWallet.vue",
    legacyIndex: 15,
    status: 'pending-view',
  },
  {
    sourceModule: "newProductLaunch",
    sourceFile: "src/router/modules/newProductLaunch.js",
    legacyPath: "/newProductLaunch",
    path: "/newProductLaunch",
    name: "newProductLaunch",
    legacyView: "@/views/newProductLaunch/index",
    legacyIndex: 2,
    status: 'migrated',
  },
  {
    sourceModule: "nodeApplication",
    sourceFile: "src/router/modules/nodeApplication.js",
    legacyPath: "/node/nodeApplication",
    path: "/node/nodeApplication",
    name: "nodeApplication",
    legacyView: "@/views/node/nodeApplication.vue",
    legacyIndex: 15,
    status: 'pending-view',
  },
  {
    sourceModule: "nodePool",
    sourceFile: "src/router/modules/nodePool.js",
    legacyPath: "/pool/nodePool",
    path: "/pool/nodePool",
    name: "nodePool",
    legacyView: "@/views/pool/nodePool.vue",
    legacyIndex: 15,
    status: 'pending-view',
  },
  {
    sourceModule: "order",
    sourceFile: "src/router/modules/order.js",
    legacyPath: "/order",
    path: "/order",
    name: "order",
    legacyView: "@/views/order/index.vue",
    legacyIndex: 2,
    status: 'migrated',
  },
  {
    sourceModule: "orderDetail",
    sourceFile: "src/router/modules/orderDetail.js",
    legacyPath: "/order/orderDetail",
    path: "/order/orderDetail",
    name: "home",
    legacyView: "@/views/order/orderDetail.vue",
    legacyIndex: 3,
    status: 'migrated',
    note: "legacy route name \"home\" preserved for compatibility",
  },
  {
    sourceModule: "pendingReceipt",
    sourceFile: "src/router/modules/pendingReceipt.js",
    legacyPath: "/order/pendingReceipt",
    path: "/order/pendingReceipt",
    name: "pendingReceipt",
    legacyView: "@/views/order/pendingReceipt.vue",
    legacyIndex: 11,
    status: 'migrated',
  },
  {
    sourceModule: "personInfo",
    sourceFile: "src/router/modules/personInfo.js",
    legacyPath: "/mine/personInfo",
    path: "/mine/personInfo",
    name: "personInfo",
    legacyView: "@/views/mine/personInfo.vue",
    legacyIndex: 13,
    status: 'pending-view',
  },
  {
    sourceModule: "phoneNumberSetting",
    sourceFile: "src/router/modules/phoneNumberSetting.js",
    legacyPath: "/mine/phoneNumberSetting",
    path: "/mine/phoneNumberSetting",
    name: "phoneNumberSetting",
    legacyView: "@/views/mine/phoneNumberSetting.vue",
    legacyIndex: 14,
    status: 'pending-view',
  },
  {
    sourceModule: "phoneRegister",
    sourceFile: "src/router/modules/phoneRegister.js",
    legacyPath: "/register/phoneRegister",
    path: "/register/phoneRegister",
    name: "phoneRegister",
    legacyView: "@/views/register/phoneRegister",
    legacyIndex: 2,
    status: 'migrated',
  },
  {
    sourceModule: "phoneRegisterTwo",
    sourceFile: "src/router/modules/phoneRegisterTwo.js",
    legacyPath: "/register/phoneRegisterTwo",
    path: "/register/phoneRegisterTwo",
    name: "phoneRegisterTwo",
    legacyView: "@/views/register/phoneRegisterTwo",
    legacyIndex: 3,
    status: 'migrated',
  },
  {
    sourceModule: "premiumRanking",
    sourceFile: "src/router/modules/premiumRanking.js",
    legacyPath: "/premiumRanking",
    path: "/premiumRanking",
    name: "premiumRanking",
    legacyView: "@/views/premiumRanking/index",
    legacyIndex: 2,
    status: 'migrated',
  },
  {
    sourceModule: "product",
    sourceFile: "src/router/modules/product.js",
    legacyPath: "/classify/product",
    path: "/classify/product",
    name: "product",
    legacyView: "@/views/product/index.vue",
    legacyIndex: 25,
    status: 'migrated',
  },
  {
    sourceModule: "recommend",
    sourceFile: "src/router/modules/recommend.js",
    legacyPath: "classify/recommend",
    path: "/classify/recommend",
    name: "recommend",
    legacyView: "@/views/classify/recommend.vue",
    legacyIndex: 12,
    status: 'migrated',
    note: "normalized from relative path classify/recommend",
  },
  {
    sourceModule: "search",
    sourceFile: "src/router/modules/search.js",
    legacyPath: "/search",
    path: "/search",
    name: "search",
    legacyView: "@/views/search/index.vue",
    legacyIndex: 17,
    status: 'migrated',
  },
  {
    sourceModule: "setting",
    sourceFile: "src/router/modules/setting.js",
    legacyPath: "/mine/setting",
    path: "/mine/setting",
    name: "setting",
    legacyView: "@/views/mine/setting.vue",
    legacyIndex: 12,
    status: 'pending-view',
  },
  {
    sourceModule: "settingMail",
    sourceFile: "src/router/modules/settingMail.js",
    legacyPath: "/mine/settingMail",
    path: "/mine/settingMail",
    name: "settingMail",
    legacyView: "@/views/mine/settingMail.vue",
    legacyIndex: 14,
    status: 'pending-view',
  },
  {
    sourceModule: "shippingAddress",
    sourceFile: "src/router/modules/shippingAddress.js",
    legacyPath: "/mine/shippingAddress",
    path: "/mine/shippingAddress",
    name: "shippingAddress",
    legacyView: "@/views/mine/shippingAddress.vue",
    legacyIndex: 12,
    status: 'pending-view',
  },
  {
    sourceModule: "specialSpike",
    sourceFile: "src/router/modules/specialSpike.js",
    legacyPath: "/specialSpike",
    path: "/specialSpike",
    name: "specialSpike",
    legacyView: "@/views/specialSpike/index",
    legacyIndex: 2,
    status: 'migrated',
  },
  {
    sourceModule: "stateNode",
    sourceFile: "src/router/modules/stateNode.js",
    legacyPath: "/node/stateNode",
    path: "/node/stateNode",
    name: "stateNode",
    legacyView: "@/views/node/stateNode.vue",
    legacyIndex: 15,
    status: 'pending-view',
  },
  {
    sourceModule: "storeDetail",
    sourceFile: "src/router/modules/storeDetail.js",
    legacyPath: "/storeDetail",
    path: "/storeDetail",
    name: "storeDetail",
    legacyView: "@/views/storeDetail/index.vue",
    legacyIndex: 21,
    status: 'pending-view',
  },
  {
    sourceModule: "superNode",
    sourceFile: "src/router/modules/superNode.js",
    legacyPath: "/node/superNode",
    path: "/node/superNode",
    name: "superNode",
    legacyView: "@/views/node/superNode.vue",
    legacyIndex: 15,
    status: 'pending-view',
  },
  {
    sourceModule: "tabbar",
    sourceFile: "src/router/modules/tabbar.js",
    legacyPath: "/index",
    path: "/index",
    name: "index",
    legacyView: "@/views/home/index.vue",
    legacyIndex: 1,
    status: 'migrated',
    note: "tabbar.js exports 4 routes",
  },
  {
    sourceModule: "tabbar",
    sourceFile: "src/router/modules/tabbar.js",
    legacyPath: "/classify",
    path: "/classify",
    name: "classify",
    legacyView: "@/views/classify/index.vue",
    legacyIndex: 1,
    status: 'migrated',
    note: "tabbar.js exports 4 routes",
  },
  {
    sourceModule: "tabbar",
    sourceFile: "src/router/modules/tabbar.js",
    legacyPath: "/shopCart",
    path: "/shopCart",
    name: "shopCart",
    legacyView: "@/views/shopCart/index.vue",
    legacyIndex: 1,
    status: 'migrated',
    note: "tabbar.js exports 4 routes",
  },
  {
    sourceModule: "tabbar",
    sourceFile: "src/router/modules/tabbar.js",
    legacyPath: "/mine",
    path: "/mine",
    name: "mine",
    legacyView: "@/views/mine/index.vue",
    legacyIndex: 1,
    status: 'pending-view',
    note: "tabbar.js exports 4 routes",
  },
  {
    sourceModule: "toBeDelivered",
    sourceFile: "src/router/modules/toBeDelivered.js",
    legacyPath: "/order/toBeDelivered",
    path: "/order/toBeDelivered",
    name: "toBeDelivered",
    legacyView: "@/views/order/toBeDelivered.vue",
    legacyIndex: 11,
    status: 'migrated',
  },
  {
    sourceModule: "transactionDetails",
    sourceFile: "src/router/modules/transactionDetails.js",
    legacyPath: "/order/transactionDetails",
    path: "/order/transactionDetails",
    name: "transactionDetails",
    legacyView: "@/views/order/transactionDetails.vue",
    legacyIndex: 4,
    status: 'migrated',
  },
  {
    sourceModule: "viewLogistics",
    sourceFile: "src/router/modules/viewLogistics.js",
    legacyPath: "/order/viewLogistics",
    path: "/order/viewLogistics",
    name: "viewLogistics",
    legacyView: "@/views/order/viewLogistics.vue",
    legacyIndex: 12,
    status: 'migrated',
  },
] as const satisfies readonly LegacyRouteDescriptor[]

export const LEGACY_ROUTE_MODULE_COUNT = 53
export const LEGACY_ROUTE_RECORD_COUNT = legacyRouteManifest.length
